# Generated by Django 2.2.1 on 2019-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='url_name',
        ),
        migrations.AddField(
            model_name='website',
            name='Title',
            field=models.CharField(default='Eureka', max_length=200),
        ),
    ]
