# Generated by Django 2.2.1 on 2019-06-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190619_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
