# Generated by Django 2.2.1 on 2019-06-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190620_0534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
